### ISSUE TITLE
Have problem with goapp serve error

### ISSUE THREAD

**Issue by chayutzee** [astaxie/beegae#19]
Please Help ! 

I'm new in golang and beego(beegae).
I'm try to following get start and have error 

![screen shot 2558-03-08 at 1 31 40 pm](https://cloud.githubusercontent.com/assets/1681564/6544892/cd295e80-c597-11e4-9a3f-40b639d6cda9.png)

**Comment by someone1** [comment]
Hmm, there was a recent update to beego that may have resulted in this. Did you enable any middleware in your application? Do you get the same error when you try out any of the examples in the  repository?

**Comment by chayutzee** [comment]
I just following the https://github.com/astaxie/beegae#getting-started . 

![screen shot 2558-03-09 at 11 23 16 pm](https://cloud.githubusercontent.com/assets/1681564/6559285/6ffdc4a8-c6b4-11e4-92f8-f5c6397ade1f.png)

I just try to run hello and appengine-angular-gotodos that in example folder and get the same error .

**Comment by chayutzee** [comment]
This is another try on beegae.  I have no idea with this error. 
![screen shot 2558-03-09 at 11 58 19 pm](https://cloud.githubusercontent.com/assets/1681564/6559845/53ff06d2-c6b8-11e4-9506-9d33c6435f5d.png)

**Comment by someone1** [comment]
There was an update to Beego which is resulting in these errors. I'll put up a fix later tonight. As of now, you can try switching your local beego repository to commit 07c628c7e9f813efc3f7e1785f667e08f2340d53 (Beegae is caught up to Version 1.4.2 of Beego, which is tagged on that commit)

**Comment by chayutzee** [comment]
Thank you very very much . I will try your solution tomorrow morning . :) 
If you fix this pls lets me kwon.

**Comment by chayutzee** [comment]
@someone1  thank you . your solution it work !! :+1: 
![screen shot 2558-03-10 at 9 33 43 am](https://cloud.githubusercontent.com/assets/1681564/6568346/9c576ffa-c708-11e4-8f2b-09ff78ac9e84.png)

**Comment by someone1** [comment]
This should now be resolved. Please re-open the issue if you are still having issues after updating your local repository.
