### ISSUE TITLE
Failed to deploy to the server

### ISSUE THREAD

**Issue by jianyunli** [astaxie/beegae#24]
I am new to Go,

I am able to use "goapp serve" to run the example in local, but using "goapp deploy" gives me the following error

go-app-builder: Failed parsing input: parser:bad import "syscall" in github.com/astaxie/beego/grace/grace.go

what could cause this? thanks

**Comment by someone1** [comment]
Thanks for the report, I'll put in a fix for this shortly.

**Comment by Jackgris** [comment]
I had no problems with the deploy with oauth, this is related to an update?

**Comment by someone1** [comment]
Of course I typo'd the fix commit to reference a different issue -_-"

Fixed from commit 6f32239c93e652abf05a9502b2a24e120a6461e7

**Comment by someone1** [comment]
Also, my apologies on the extended "shortly" - although I use beegae in production I have not been in a spot recently where I was able to dedicate time to this fix.
