### ISSUE TITLE
Error when using goapp get

### ISSUE THREAD

**Issue by frankcarey** [astaxie/beegae#27]
I have an existing 'hello world' app on beego 1.6, but calling `goapp get github.com/astaxie/beegae` causes an error before I can proceed with the rest of the instructions.

```
# github.com/astaxie/beegae/session
github.com/astaxie/beegae/session/sess_cookie.go:186: cannot use cookiepder (type *CookieProvider) as type Provider in argument to Register:
	*CookieProvider does not implement Provider (wrong type for SessionDestroy method)
		have SessionDestroy(string) error
		want SessionDestroy(context.Context, string) error
```

**Comment by someone1** [comment]
This has now been fixed with the latest release of beegae. Please try again and  reopen the issue if the issue persists.

You also no longer are required to use `goapp` and can use `go`

Thank you.
