### ISSUE TITLE
Beego 1.6 uses a lot of modules not supported by AppEngine

### ISSUE THREAD

**Issue by frankcarey** [astaxie/beegae#28]
So, I've been messing around for the last few hours trying to get beego 1.6 working on AppEngine (note that I was NOT using beegae, but a forked version of beego 1.6 to see what it would take to run it on AppEngine..)

I saw that 1.6 added a Context interface and I was curious to see if I could make that work but before I could even start testing that out I ran into a few issues with unsafe packages being imported.

Here are the packages AppEngine doesn't allow:

###net (net/http is OK apparently , just not "net")
```
./app.go:19:	"net"
./context/context.go:34:	"net"
./httplib/httplib.go:44:	"net"
./logs/conn.go:20:	"net"
./logs/es/es.go:7:	"net"
./logs/smtp.go:21:	"net"
```

### syscall
```
./grace/grace.go:51:	"syscall"
./grace/listener.go:6:	"syscall"
./grace/server.go:14:	"syscall"
```
If not using grace, then in theory this could be deleted, but grace is imported in a couple more places..

```
./admin.go:26:	"github.com/astaxie/beego/grace"
./app.go:26:	"github.com/astaxie/beego/grace"
```

I'm sure this is the reason that the beegae project exists in the first place, but there seemed to be a suggestion in the issues here that once Context was implemented this wouldn't be needed anymore.

**Comment by jelmerdereus** [comment]
I don't know where this is going @frankcarey . I use beegae for the exact reason that this is a platform that supports GAE. And the above issue doesn't exist in this repo so should be in Beego.

**Comment by someone1** [comment]
There would be some changes required on beego (hopefully nonbreaking aside from implementing a [context.Context](https://godoc.org/golang.org/x/net/context)) but it doesn't seem like that will happen anytime soon. You should probably use this package (and contribute if you notice any issues!) for now.
